# This is a basic workflow to help you get started with Actions

name: zfprotectors

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # 切换setup-node环境
      - name: Checkout
        uses: actions/setup-node@v3
        with:
          node-version: "12.x"
      
      # 初始化npm包
      - name: Install Node Modules
        run: |
          npm install yarn -g
          yarn
          yarn test
      
      # 执行build
      - name: Build
        run: yarn build
      
      - name: lookup dist
        run: ls docs/.vuepress/
      
      # 发布到目标服务器
      - name: scp-deployer
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }} # 公网ip
          username: ${{ secrets.REMOTE_USERNAME }} # 用户名
          password: ${{ secrets.REMOTE_PASS }} # 密码
          source: "docs/.vuepress/dist" # 发送文件
          target: "/home/ubuntu/" # 目标目录
