# This is a basic workflow to help you get started with Actions

name: zfprotectors

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      
      - name: mv dist
        run: |
          mv docs/.vuepress/dist .
      
      # 发布到目标服务器
      - name: scp-deployer
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }} # 公网ip
          username: ${{ secrets.REMOTE_USERNAME }} # 用户名
          password: ${{ secrets.REMOTE_PASS }} # 密码
          source: "dist" # 发送文件
          target: "/home/ubuntu" # 目标目录
